// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _requiredEnv(String key) {
    final value = dotenv.env[key]?.trim();
    if (value == null || value.isEmpty) {
      throw StateError('Variavel obrigatoria ausente no .env: $key');
    }
    return value;
  }

  static String? _optionalEnv(String key) {
    final value = dotenv.env[key]?.trim();
    if (value == null || value.isEmpty) {
      return null;
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_WEB_API_KEY'),
    appId: _requiredEnv('FIREBASE_WEB_APP_ID'),
    messagingSenderId: _requiredEnv('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _requiredEnv('FIREBASE_PROJECT_ID'),
    authDomain: _optionalEnv('FIREBASE_WEB_AUTH_DOMAIN'),
    storageBucket: _optionalEnv('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_ANDROID_API_KEY'),
    appId: _requiredEnv('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: _requiredEnv('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _requiredEnv('FIREBASE_PROJECT_ID'),
    storageBucket: _optionalEnv('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_IOS_API_KEY'),
    appId: _requiredEnv('FIREBASE_IOS_APP_ID'),
    messagingSenderId: _requiredEnv('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _requiredEnv('FIREBASE_PROJECT_ID'),
    storageBucket: _optionalEnv('FIREBASE_STORAGE_BUCKET'),
    iosClientId: _optionalEnv('FIREBASE_IOS_CLIENT_ID'),
    iosBundleId: _optionalEnv('FIREBASE_IOS_BUNDLE_ID'),
  );
}