type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Class @table {
  user: User!
  name: String!
  startTime: String!
  endTime: String!
  daysOfWeek: String!
  location: String!
  professorName: String
  professorEmail: String
  courseCode: String
  description: String
}

type Assignment @table {
  user: User!
  class: Class
  title: String!
  dueDate: Timestamp!
  status: String!
  description: String
  priority: String
}

type Exam @table {
  user: User!
  class: Class
  title: String!
  examDate: Timestamp!
  startTime: String!
  endTime: String!
  location: String
  notes: String
}

type Event @table {
  user: User!
  title: String!
  eventDate: Timestamp!
  startTime: String!
  endTime: String!
  description: String
  location: String
}